### ISSUE TITLE
issue with a Lund APIS image

### ISSUE THREAD

**Issue by hermaion** [papyri/navigator#105]
The digital picture for https://papyri.info/apis/lund.apis.118 is not displayed in the page, likely because the image link http://papyri.info/images/f1/P.Lund.00111r generates a proxy error, as pointed out by Rodney Ast. James Cowey suggests that perhaps the link should be changed into https://papyri.info/dclp/p.bagnall;;1/images, which however gives a black page.

**Comment by samosafuz** [comment]
The image lives [here](https://papyri.info/apis/lund.apis.118/images): I'll make the update to the DCLP file myself today. Thanks for pointing it out.

**Comment by samosafuz** [comment]
The APIS entry will still be out of date, unless someone with a better understanding of the images file/folder structure can fix whatever is broken in the current target addresses.
