### ISSUE TITLE
Navigator only vaguely useful

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#113]
In chrome when I try to search I get the following screen:

![Bildschirmfoto 2021-10-07 um 12 04 08](https://user-images.githubusercontent.com/612992/136364009-1644f306-c393-4fc6-b8e2-cfb2d07e73b2.png)

DDbDP browse sometimes loads properly
HGV browse sometimes repsonds to refresh to load.
If I click on a series e.g.

https://papyri.info/search?SERIES=O.Sarga

I get the error pictured above
ERR_HTTP2_PROTOCOL_ERROR

In Firefox I get the following 

![Bildschirmfoto 2021-10-07 um 12 07 44](https://user-images.githubusercontent.com/612992/136364388-72478e52-fbbf-4346-aae4-07d822701725.png)

Refreshing is so far not successful at all.

Obviously the sooner this can be made to work as usual the better.

**Comment by hcayless** [comment]
We're experiencing periodic out-of-memory errors. We've put in better monitoring to figure out what's going on.
