### ISSUE TITLE
404 errors for existing HGV files

### ISSUE THREAD

**Issue by samosafuz** [papyri/navigator#114]
A large [pull request](https://github.com/papyri/idp.data/pull/262) that Xwalked new HGV metadata for various journal issues (e.g., BASP, Tyche, JJP) was merged a few days ago. 

After merging, I can confirm that all the files synced and displayed correctly (I was updating PN hyperlinks in James' [journalProgress](https://docs.google.com/spreadsheets/d/11OVnpAaRqeIbkAa7FgeKWrrdgwm-aXnhGi0Qw9Y7FTQ/edit#gid=1849710518) spreadsheet, and checked each one).

Now, however, several of these files are producing 404 errors:

<img width="732" alt="Screen Shot 2021-10-26 at 10 55 23 AM" src="https://user-images.githubusercontent.com/61889129/138905300-ffa75045-d953-456f-ad0a-76de893fb544.png">

The error is not systematic, but appears to be worse with BASP. These, for example, do not display:

- 764352
- 764353
- 764354
- 764355
- 764356
- 832323

832328, on the other hand, is fine, while 832323 is broken. 

Perhaps a re-index will solve the issue. In the meanwhile, DDB transcriptions can't be added.

**Comment by hcayless** [comment]
I think there's an error with a couple of BASP documents that may be preventing them all from being fully processed. I'm attempting a fix.

**Comment by hcayless** [comment]
These seem to be fixed
