### ISSUE TITLE
Previous record / Next record non functional.

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#117]
Was looking at:

https://papyri.info/search?DATE_MODE=LOOSE&DOCS_PER_PAGE=15&SERIES=p.petr.kleon&COLLECTION=ddbdp&TRANSL=en

to verify your fix for #11

Nice. Clicked on both Previous record and Next record. That gives me a "HTTP Status 404 – Not Found"

Same for a word search. So, I suspect there must be a little bug ithat is affecting the Previous record / Next record function across all searches.

**Comment by hcayless** [comment]
Looks like there was a regression in that old code (which is ancient and hacky and which I'm itching to rewrite). Fixed.
