### ISSUE TITLE
Sync for translations needs to call indexing on the related record

### ISSUE THREAD

**Issue by hcayless** [papyri/navigator#122]
So if https://papyri.info/hgvtrans/9025/source gets updated, the indexer needs to run on `http://papyri.info/ddbdp/bgu;1;28/source`. This could happen either in the sync code or possibly should be implemented in the indexer itself.

**Comment by hcayless** [comment]
I believe this is now working correctly.

**Comment by jcowey** [comment]
I noticed you closed this. I finalized two translations:

https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/78091.xml

```
            <idno type="filename">78091</idno>
            <idno type="TM">78091</idno>
            <idno type="HGV">78091</idno>
            <idno type="ddb-hybrid">p.bingen;;132</idno>
```

Which I hoped would appear alongside HGV and DDB files in 

https://papyri.info/ddbdp/p.bingen;;132

```
<idno type="filename">p.bingen.132</idno>
<idno type="ddb-perseus-style">0254;;132</idno>
<idno type="ddb-hybrid">p.bingen;;132</idno>
<idno type="HGV">78091</idno>
<idno type="TM">78091</idno>
```

and

https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/754948.xml

```
            <idno type="filename">754948</idno>
            <idno type="TM">754948</idno>
            <idno type="HGV">754948</idno>
            <idno type="ddb-hybrid">zpe;206;182_2</idno>
```

Which I hoped would appear alongside HGV and DDB files in 


https://papyri.info/ddbdp/zpe;206;182_2
```
<idno type="filename">zpe.206.182_2</idno>
<idno type="ddb-hybrid">zpe;206;182_2</idno>
<idno type="HGV">754948</idno>
<idno type="TM">754948</idno>
```


It appears that this has not happened. Maybe I am getting my wires crossed and expecting something that
you were not coding for. Would you please have a look.

**Comment by hcayless** [comment]
I think this is working as expected now, but will keep an eye on it.
