### ISSUE TITLE
Numbering in Arabic only texts

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#13]
Would you please merge from papyri.info to dev.papyri.info to include this text (Arabic only), which I have just added to papyri.info

http://papyri.info/ddbdp/p.worp;;65

could you please display the line numbers as in the edition, which you will find in .doc form here:

http://147.142.225.252/Xcoded/PWorp/Text%2065def.doc

i.e. Arabic numbers without a dot (neither before nor after the numeral)

and running RTL 

and as in the rest of papyri.info in fives (5, 10, 15, 20 etc)

This seems to be relatively standard practice in modern Arabic editions. I have spoken to Lajos and Usama who were alright with this. (Not to say that others will be. There will almost certainly be others who do not like it, but it would be something to show)

**Comment by jcowey** [comment]
I notice only now that when one looks at the apparatus of 
http://papyri.info/ddbdp/p.worp;;65
It reads RTL. Yet another thing where my gut reaction would be to say that it should read LTR.

Is this a knock on effect of where line numbering is placed and interpreted?

Maybe best to leave this as a problem to be looked at and solved later

**Comment by hcayless** [comment]
I think the numbering is fixed (checked against P.Worp. 65 in the papyr room). I'm not sure what the complaint about the apparatus is, or whether it still applies.
