### ISSUE TITLE
Surfacing translations alongside text and metadata in DCLP

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#131]
I suspect that this may have something to do with #122. That issue solved existing problems.

Translations that are entered through papyri.info are now **successfully synced and displayed** for DDB / HGV records.

Received a mail from Holger Essler (19.3.2022), who had noticed that translations he had entered to the system for DCLP records are not being displayed in the HTML presentation of Metadata and Text.

Would you please look at the following DCLP records

|DCLP HTML|trans_EpiDoc file|
|----|----|
|https://papyri.info/dclp/62505|https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/62505.xml|
|https://papyri.info/dclp/62391|https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/62391.xml|
|https://papyri.info/dclp/62411|https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/62411.xml|
|https://papyri.info/dclp/62419|https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/62419.xml|
|https://papyri.info/dclp/62481|https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/62481.xml|

The DCLP record does not display the translations that exist in: https://github.com/papyri/idp.data/tree/master/HGV_trans_EpiDoc.
(Remember **ALL** translations go to https://github.com/papyri/idp.data/tree/master/HGV_trans_EpiDoc, irrespective of whether they translate documents or non-dcoumentary texts)

I suspect that, because the structure of DCLP files are somewhat different than those in DDB / HGV, some tweaks to the code will be required before translations in DCLP are displayed.

Would be great if you could make sync work in this sort of situation. Or is it only a matter of a re-index?

**Comment by hcayless** [comment]
Looks fixed.
