### ISSUE TITLE
Display of adjacent square brackets bug

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#133]
https://papyri.info/ddbdp/p.sijp;;12d

In line 1 we see: 
![Bildschirmfoto 2022-04-02 um 17 30 22](https://user-images.githubusercontent.com/612992/161390180-ec98f883-79e4-4552-820d-4c8cc2a11269.png)

[⁦ -ca.?- ⁩] [Ἑ]ρ̣με̣ί̣ν̣ωι[(*)](https://papyri.info/ddbdp/p.sijp;;12d#to-app-choice01) βασιλικῶι γ̣[ραμματεῖ ⁦ -ca.?- ⁩]

we would like to see:

[⁦ -ca.?-  Ἑ]ρ̣με̣ί̣ν̣ωι[(*)](https://papyri.info/ddbdp/p.sijp;;12d#to-app-choice01) βασιλικῶι γ̣[ραμματεῖ ⁦ -ca.?- ⁩]

The underlying XML is at: https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.sijp/p.sijp.12d.xml#L57

```
<lb n="1"/><gap reason="lost" extent="unknown" unit="character"/> <choice><reg><supplied reason="lost">Ἑ</supplied>ρμίνωι</reg><orig><supplied reason="lost">Ἑ</supplied><unclear>ρ</unclear>μ<unclear>είν</unclear>ωι</orig></choice> βασιλικῶι <unclear>γ</unclear><supplied reason="lost">ραμματεῖ</supplied> <gap reason="lost" extent="unknown" unit="character"/> 
```

I think that some bug must have slipped into the XSLT Make HTML transformation. Would be great if you would fix this.

**Comment by jcowey** [comment]
https://papyri.info/ddbdp/bgu;1;5 offers further evidence of this behaviour.

col2 lin23: ἐπὶ Ἡρακλείδου τ  ̣[  ̣  ̣  ̣  ̣  ̣][ Ἀχι]λλέως αἰτησαμένου   ̣[- ca.9 -] 

which we would like to see as

ἐπὶ Ἡρακλείδου τ  ̣[  ̣  ̣  ̣  ̣  ̣ Ἀχι]λλέως αἰτησαμένου   ̣[- ca.9 -] 

with underlying XML being at: https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/bgu/bgu.1/bgu.1.5.xml#L141:

```
<lb n="23"/>ἐπὶ Ἡρακλείδου τ<gap reason="illegible" quantity="1" unit="character"/><gap reason="lost" quantity="5" unit="character"/><supplied reason="lost"> Ἀχι</supplied>λλέως αἰτησαμένου <gap reason="illegible" quantity="1" unit="character"/><gap reason="lost" quantity="9" unit="character"/> 
```

And also in col3 lin17 where we see:

των [  ̣  ̣  ̣][ακ]ολουθη[⁦ -ca.?- ⁩]

which we wold like to see as

των [  ̣  ̣  ̣ ακ]ολουθη[⁦ -ca.?- ⁩]

with underlying XML being at: https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/bgu/bgu.1/bgu.1.5.xml#L186:

```
<lb n="17"/>των <gap reason="lost" quantity="3" unit="character"/><supplied reason="lost">ακ</supplied>ολουθη<gap reason="lost" extent="unknown" unit="character"/> 
```

**Comment by hcayless** [comment]
This was an unwelcome side effect of the LTR support I was working on. I believe I have now fixed it.
