### ISSUE TITLE
Bug in DDbDP browsing

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#135]
If one browses by https://papyri.info/browse/ddbdp/

then one sees that "upz" is missing "p.capasso" is missing. 

If one then browses by https://papyri.info/browse/hgv/

one can get to UPZ and P.Capasso but the files with Greek texts are not shown. 

Something must have gone slightly wrong with the last re-index. We have had this behaviour before, I seem to remember, but could not find the old issue for it.

Would you please try to fix this as soon as you can.

**Comment by hcayless** [comment]
Fixed.
