### ISSUE TITLE
chr.wilck.458 (TM 20195) has disappeared

### ISSUE THREAD

**Issue by enury** [papyri/navigator#147]
The TM search for 20195 is not giving any result, and the [page ](https://papyri.info/ddbdp/chr.wilck;;458) referenced in [Trismegistos ](https://www.trismegistos.org/tm/detail.php?tm=20195) gives an error message.

However, both some metadata and a transcription file can still be accessed:
- [https://papyri.info/ddbdp/bgu;1;113/source](https://papyri.info/ddbdp/bgu;1;113/source)
- https://papyri.info/ddbdp/chr.wilck;;458/source

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/commit/82b496213c0cae400d6cc843b9898c368eea037e

should probably do the trick.

**Comment by jcowey** [comment]
https://papyri.info/ddbdp/chr.wilck;;458

now displays

https://papyri.info/ddbdp/bgu;1;113

will work once a new re-index has been done.

https://papyri.info/hgv/20195

also now works

**Comment by jcowey** [comment]
@enury  can you please confirm that everything is now as expected.

**Comment by enury** [comment]
dear @jcowey, yes everything is working as expected. For good measure I also tried <https://papyri.info/trismegistos/20195> and it worked as well.

Thank you for the prompt reaction!

**Comment by jcowey** [comment]
Now OK
