### ISSUE TITLE
Reindex and fix sync, please

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#15]
Would you please reindex again, Hugh.
In the last three days work that has been done has not be reflected in the browse version of the texts. E.g. 
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.cair.zen/p.cair.zen.3/p.cair.zen.3.59377.xml
was changed but is not visible in 
http://papyri.info/ddbdp/p.cair.zen;3;59377

Sync also does not seem to be performing correctly. It did so briefly last week when you fixed it. It seems, however, to have struck difficulties again.

Would you please have a look and try to fix it.

Many thanks

James

**Comment by hcayless** [comment]
Looks like there was some repo corruption interfering with the sync. I’ve fixed it, and I’m running a full reindex now.

**Comment by hcayless** [comment]
Sync appears to be running properly again.
