### ISSUE TITLE
DCLP Author/Work Indexing

### ISSUE THREAD

**Issue by samosafuz** [papyri/navigator#151]
I went looking this morning for a fragment of the Hellenica Oxyrhynchia that was entered in DCLP at last summer's Ottawa workshop, whose dclp-hybrid `<idno>` and TM `<idno>` I'd forgotten. I expected to find it by using the DCLP tab on the PN browser to navigate to `Anonymus` (author) and `Hellenica Oxyrhynchia` (work), but that link produced only 3 hits, none of which was the file I sought (which turned out to be TM 59483):

https://papyri.info/dispatch/search?AUTHOR=Anonymus&WORK=Hellenica+Oxyrhynchia

I immediately assumed that something was amiss in the metadata, but found precisely the metadata in the `<div>` with `@subtype="ancientEdition"` that I was expecting:

```
         <div type="bibliography" subtype="ancientEdition">
            <listBibl>
               <bibl type="publication" subtype="ancient">
                  <author xml:lang="grc"
                          ref="http://data.perseus.org/catalog/urn:cts:greekLit:tlg0558">Anonymus</author>
                  <title type="main"
                         level="m"
                         ref="http://www.trismegistos.org/authorwork/2177">Hellenica Oxyrhynchia</title>
               </bibl>
            </listBibl>
         </div>
```

I doubled-checked via xQuery, which indicated both that `<title>` with the value `Hellenica Oxyrhynchia` and for `@ref` with the value `http://www.trismegistos.org/authorwork/2177` should return four hits. Only TM 59483 was missing, in other words. 

This isn't a major issue by any stretch, but I'm flagging it in case there have been other bugs in the indexer that you're tracking; I presume that's where the issue lies.

**Comment by hcayless** [comment]
Not sure what the problem was, but it seems to be fixed now.
