### ISSUE TITLE
 Metadata failing to appear when file is opened in the editor

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#153]
Putting in a marker here for a problem with `Open in editor`

https://github.com/papyri/sosol/issues/344

When there is a full complement of metadata, text, apis etc only text is being presented. The user is even being offfered the possibility of creating new metadata.

**Comment by hcayless** [comment]
I think there's a problem with the numbers server. I'll get on it as soon as I'm in to work.

**Comment by hcayless** [comment]
Think this is now fixed.
