### ISSUE TITLE
p.koeln;14,584 behaving strangely

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#16]
Hello, Hugh, would you please take a look at the following and see if you can fix it, or let me know what has to be done to fix it.

http://papyri.info/hgv/697591/source
works fine
http://papyri.info/hgv/697591/
produces
HTTP Status 404 -

type Status report

message

description The requested resource () is not available.
Apache Tomcat/7.0.16

The file
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.koeln/p.koeln.14/p.koeln.14.584.xml
looks fine to me as far as idnos is concerned
the matching file
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV698/697591.xml
also looks good.

Why does 
http://papyri.info/ddbdp/p.koeln;14;584
and
http://papyri.info/hgv/697591
produce

HTTP Status 404 -

type Status report

message

description The requested resource () is not available.

?? strange ??

**Comment by hcayless** [comment]
Fixed.
