### ISSUE TITLE
File got lost somewhere in the machinery

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#17]
Hello Hugh, I had what looked like a time out on finalization. You can see the details in
https://github.com/papyri/sosol/issues/31
Somehow or other this file
http://papyri.info/editor/publications/50138
has not been picked up by sync and thus not incorporated into the master files.
Would you please have a look and try to fix it in such a way to ensure the 
p.cair.mich.2.12f_r.xml
is included in 
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.cair.mich/p.cair.mich.2
and is displayed next to the metadata at
http://papyri.info/hgv/397533

Thanks

**Comment by jcowey** [comment]
Over the last three days any file that was finalized has not been picked up properly by sync, despite the appearance that sync is updating every hour. Here are the affected files:
http://papyri.info/editor/publications/49286
http://papyri.info/editor/publications/47811
taken (submitted identifiers) from users/esthergarel

http://papyri.info/editor/publications/50036
http://papyri.info/editor/publications/50027
http://papyri.info/editor/publications/51265
taken (submitted identifiers) from from users/james.cowey

When they go through finalization they get new "publications/ids"
e.g.
http://papyri.info/editor/publications/50027
becomes
http://papyri.info/editor/publications/50138

Can you please fix these so that they show up properly.

**Comment by hcayless** [comment]
There are clearly some underlying issues, I think with the git repos, that are causing this. I noticed last week that a pull into idp.data from canonical results in a huge number of broken refs being reported. I suspect this is causing some issues for processes like sync.

**Comment by jcowey** [comment]
OK please let me know if there is anything I can do to help. Or have I made commits that are causing trouble?

**Comment by hcayless** [comment]
@jcowey I don't think it's you. I've pushed a change to the [gitwrapper](https://github.com/sosol/gitwrapper/commit/c51db70c7671908d06c70c9689da178cb21f3170) code that I hope will help with this. We probably still need to deal with all the missing refs, which probably can just be removed. I want to make sure it can be done safely first though.

**Comment by jcowey** [comment]
Many thanks for making all the files appear as they should. Super!!
looked at your changes from pn-sync => pnsync and pn-dispatch => pndispatch
in
https://github.com/papyri/navigator/commit/892b70bebdcab90615d0cfc757112c0b0f6463ea
etc.
Bemused I am, but if it has the desired effect, then more power to your arm! ;)
Anyway thanks again for all your efforts.

**Comment by jcowey** [comment]
@hcayless Closing this.
