### ISSUE TITLE
Heid.Arab

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#19]
Hugh, would it be possible for you to fix the following quickly (or does it need a full re-index)?
This weekend I created a new series: p.heid.arab
https://github.com/papyri/idp.data/commit/25caeb19dce6cc6237a8793522ef64c82658b1b7
With this i renamed two files
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.heid.arab/p.heid.arab.1/p.heid.arab.1.1.xml
and
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.heid.arab/p.heid.arab.1/p.heid.arab.1.3.xml
with there respective metadata files
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV46/45353.xml
and
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV107/106482.xml

Now 
http://papyri.info/hgv/45353
and
http://papyri.info/hgv/106482
display nicely, but without relevant Arabic text.
http://papyri.info/ddbdp/p.heid.arab;1;1
and
http://papyri.info/ddbdp/p.heid.arab;1;3
return

> HTTP Status 404 -
> type Status report
> message
> description The requested resource () is not available.
> Apache Tomcat/7.0.16

It would be really great to have this showing today if possible. Would facilitate working with Andreas Kaplony towards getting Arabic into papyri.info.

**Comment by hcayless** [comment]
I'll do what I can. I'm at the Triangle Scholarly Communications Institute
until Thursday, which is an all-day thing, so I can't promise I can deal
with it before that ends.

On Mon, Oct 10, 2016 at 10:39 AM, James M.S. Cowey <notifications@github.com

**Comment by jcowey** [comment]
thanks, did not realise you were away

**Comment by hcayless** [comment]
I think it will entail a reindex, but I can probably kick one off this
evening.

On Mon, Oct 10, 2016 at 11:37 AM, James M.S. Cowey <notifications@github.com

**Comment by jcowey** [comment]
Many thanks indeed!!
http://papyri.info/ddbdp/p.heid.arab;1;1
looks exactly as I had hoped it would
