### ISSUE TITLE
p.petr;3;42 error

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#25]
I get expected hits searching for words in p.petr;3;42

http://papyri.info/search?STRING1=%CF%80%CE%BB%CE%B5%CE%BF%CE%BD%CE%B1%CE%BA%CE%B9%CF%83&target1=TEXT&no_caps1=on&no_marks1=on&page=3

 but the html page does not display

http://papyri.info/ddbdp/p.petr;3;42/?q=SUBSTRING:(%CF%80%CE%BB%CE%B5%CE%BF%CE%BD%CE%B1%CE%BA%CE%B9%CF%83)&rows=3&start=41&fl=id%2Ctitle&fq=transcription_ngram_ia%3A%28%CF%80%CE%BB%CE%B5%CE%BF%CE%BD%CE%B1%CE%BA%CE%B9%CF%83%29&sort=series+asc%2Cvolume+asc%2Citem+asc&p=42&t=52

Instead, I find

HTTP Status 404 -

type Status report

message

description The requested resource () is not available.
Apache Tomcat/7.0.16

**Comment by hcayless** [comment]
This is one of those horrible aggregations, but seems fixed.
