### ISSUE TITLE
Translation syncing

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#29]
This issue concerns http://papyri.info/ddbdp/o.berenike;3;333 . I voted on and finalized the translation of the Duke text, but the syncing mechanism doesn't seem to have pushed the translation through to  the HTML.

**Comment by jcowey** [comment]
The relevant translation file is:
https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/641821.xml

**Comment by hcayless** [comment]
Think this is now fixed.
