### ISSUE TITLE
pn-xslt Rake task should lock XSLT revision

### ISSUE THREAD

**Issue by ryanfb** [papyri/navigator#30]
https://github.com/papyri/navigator/blob/master/pn-xslt/Rakefile

Currently, we'll wind up with whatever happens to be on EpiDoc SVN trunk. So it's impossible to know from the code what's running in prod. Ideally, we should lock SoSOL to the same revision (so, either lock PN back to SoSOL's revision or update SoSOL's revision): https://github.com/sosol/sosol/blob/master/config/externals.yml

**Comment by ryanfb** [comment]
We're currently using `r2168` on production.

**Comment by hcayless** [comment]
Think this has been obsoleted now that Stylesheets checkout is managed via an Ansible Playbook. The Rake task can stick around for development convenience.
