### ISSUE TITLE
"About: DDbDP" on "About" page points to broken link

### ISSUE THREAD

**Issue by ryanfb** [papyri/navigator#32]
On: http://papyri.info/docs/about

"About: DDbDP" in the footer points to http://idp.atlantides.org/trac/idp/wiki/DDBDP instead of http://papyri.info/docs/ddbdp (as it does on most other pages)

Spotted by @gabrielbodard.

**Comment by hcayless** [comment]
Looks like the page hadn't been refreshed since we changed the template, so it was stuck on the old version. I deleted the HTML version so it would re-generate.
