### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by ryanfb** [papyri/navigator#33]
Soon (October 2017), Chrome (version 62) will start showing warnings for all form inputs on non-HTTPS sites: http://www.zdnet.com/article/google-tightens-noose-on-http-chrome-to-stick-not-secure-on-pages-with-search-fields/

LetsEncrypt might be the way to go with this, though that assumes we can successfully configure automatic renewal (see https://letsencrypt.org/2015/11/09/why-90-days.html).

**Comment by paregorios** [comment]
FWIW, Pleiades has been running under a Let's Encrypt cert for over a year with no difficulties.

**Comment by jcowey** [comment]
Is this still relevant in the light of 
https://github.com/papyri/idp.data/issues/266

having been carried out and the ticket closed?

**Comment by ryanfb** [comment]
Yes, we've been running HTTPS with LetsEncrypt in production for some time now, so this can be closed out.
