### ISSUE TITLE
Duplicated transcription on p.lond.1.113-12D

### ISSUE THREAD

**Issue by ryanfb** [papyri/navigator#35]
See: http://papyri.info/ddbdp/p.lond;1;113,12D

The DDbDP transcription is displayed twice, for some reason.

**Comment by hcayless** [comment]
The DDb files use `113,12D` style (https://github.com/papyri/idp.data/blob/a24815df639e9e90f3d0a67b4e0d2a8544266bc1/DDB_EpiDoc_XML/p.lond/p.lond.1/p.lond.1.113-12D.xml#L16), while the HGV record uses `113-12D` (https://github.com/papyri/idp.data/blob/a24815df639e9e90f3d0a67b4e0d2a8544266bc1/HGV_meta_EpiDoc/HGV39/38887.xml#L13). One or the other will need to be changed. This occurs in other P.Lond documents too.

**Comment by jcowey** [comment]
Fixed by:
https://github.com/papyri/idp.data/commit/ea7c108da5e3462471c9d456bf8aa336de65677d
and
https://github.com/papyri/idp.data/commit/157178256935c64c254af84166323e1253e6ba91
