### ISSUE TITLE
Apparatus does not appear in dev.papyri.info files

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#36]
Apparatus does not appear in http://dev.papyri.info/dclp/128922.
When I view this is looks like:
![bildschirmfoto 2019-01-17 um 14 02 33](https://user-images.githubusercontent.com/612992/51320618-afcad900-1a60-11e9-8163-9eed131dc1ea.png)

If one compares http://litpap.info/dclp/128922
One sees:
![bildschirmfoto 2019-01-17 um 14 04 57](https://user-images.githubusercontent.com/612992/51320679-eb65a300-1a60-11e9-8bdb-8f4ab142ed96.png)

**Comment by jcowey** [comment]
It is not only the DCLP files that are affected. DDbDP files in dev.papyri.info also do not display apparatus.
e.g.
http://dev.papyri.info/ddbdp/bgu;1;4

cf.

http://papyri.info/ddbdp/bgu;1;4

**Comment by jcowey** [comment]
There are a number of aspects of how the text is displayed that are not the same as in papyri.info. E.g. g types are displayed as ((stauros)) rather than the sign; text breaking off is displayed as [- - -] instead of -- -- -- -- -- -- ; underdots are treated differently.
We are used to seeing 
![bildschirmfoto 2019-01-17 um 14 13 44](https://user-images.githubusercontent.com/612992/51321094-2ddbaf80-1a62-11e9-8e5d-0a5fc1fc1e00.png)
but in dev we see 
![bildschirmfoto 2019-01-17 um 14 13 33](https://user-images.githubusercontent.com/612992/51321115-39c77180-1a62-11e9-939e-3f5ee248e102.png)

**Comment by hcayless** [comment]
I'm thinking something must have gone wonky when I merged the DCLP stylesheets with the papyri.info ones. Will check into it.

**Comment by hcayless** [comment]
Refreshing the EpiDoc stylesheets seems to have fixed the issues @jcowey identified.
