### ISSUE TITLE
Filter behaviour

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#37]
First of all the new reloading does seem to have solved the problems mentioned in #36

My question was: show me all files where Homerus is the author and there is a text div with content.

Actions taken.
Navigate via authors
http://dev.papyri.info/authors
http://dev.papyri.info/authors#H
http://dev.papyri.info/dispatch/search?AUTHOR=Homerus
nice 1689 hits
now using (at the bottom)
Has Transciptions and choosing (true 37) [which seems about right]
I arrive at
http://dev.papyri.info/dispatch/search?TRANSC=true&DATE_MODE=LOOSE&DOCS_PER_PAGE=15
which displays ALL texts across DDB and DCLP which have a transcription.

Would be nice to arrive at the 37.

**Comment by hcayless** [comment]
I noticed this behavior yesterday when looking for the Bankes Homer papyrus. It happens on the LitPap site too, but definitely needs to be fixed.

**Comment by jcowey** [comment]
Indeed it does happen on the LitPap site. Would indeed be great if you can fix it. Thanks

**Comment by hcayless** [comment]
Works now.
