### ISSUE TITLE
TM Number search not working for DCLP files

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#38]
http://dev.papyri.info/
now call up TM number search
type in 64127 (TM number for a DCLP record) hit enter button.
Leads to 
Not Found
The requested URL /dclp/64127 was not found on this server.

Apache/2.2.15 (Scientific Linux) Server at papyri.info Port 80

this pushes us through to 
papyri.info/dclp/64127 NOT dev.papyri.info

Does that mean that when this goes live it WILL in fact work? See below.

**Comment by jcowey** [comment]
If on the other hand one enters a TM number for an HGV / DDbDP record, such as 8989. Then one does arrive at:
http://papyri.info/ddbdp/bgu;1;225
(note that it is going to papyri.info NOT dev.papyri.info)

**Comment by hcayless** [comment]
Works now. This boils down to a configuration issue.
