### ISSUE TITLE
Display of "Header" in DCLP

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#42]
Using the same definition of "Header" as in #41, there is a further little improvement that would be nice.

http://dev.papyri.info/dclp/65294
`O. Strasb. . 1 807 = Trismegistos 65294 = LDAB 6538`
differs from
http://litpap.info/dclp/65294
`O. Strasb. . 1 807 = Trismegistos 65294 = LDAB 6538 = HGV O.Strasb. 1 807 = Trismegistos 65294`

**Comment by jcowey** [comment]
First the `O. Strasb. . 1 807` in both dev and litpap should really be `O. Strasb. 1 807`.

The display of HGV metadata where it is also available should, please, be present.

What I think would be best for the "Header" would be 
` O. Strasb. 1 807 = Trismegistos 65294 = LDAB 6538 = HGV O.Strasb. 1 807`
I do not think we need Trismegistos mentioned twice.

And it would be good to have the HGV metadata presented alongside the DCLP metadata as is the case in 
http://litpap.info/dclp/65294

**Comment by hcayless** [comment]
Fixed previously
