### ISSUE TITLE
Biblio search not functioning properly

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#43]
As of today (15 May 2019) the Biblio search does not function, as far as I can see.

http://papyri.info/bibliosearch

I entered the name Hagedorn

![Bildschirmfoto 2019-05-15 um 11 54 09](https://user-images.githubusercontent.com/612992/57766743-338f8c00-7708-11e9-91a2-95c12a5cc06d.png)

Is the return.
The TM# with a box at the top left seems strange to me.

**Comment by hcayless** [comment]
Fixed. See http://papyri.info/bibliosearch?q=Hagedorn

**Comment by jcowey** [comment]
That above search gives returns which look good intially.

**1668** hits on "Hagedorn 1967". is not right. 

The returns always usd to be on the generous side (AND / OR thing I think), but not **that** generous.

Would you please look again. Would be great to have the hits down to a manageable number.

**Comment by hcayless** [comment]
Fixed. The mechanism for setting the default to AND changed in Solr, and it was defaulting to OR.
