### ISSUE TITLE
Previous record next record not working

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#44]
If you call up
http://dev.papyri.info/search?&COLLECTION=dclp&SERIES=p.heid&VOLUME=1
then go to the first record
http://dev.papyri.info/dclp/59735?rows=2&start=0&fl=id,title&fq=collection:dclp&fq=(ddbdp_series:p.heid+OR+hgv_series:p.heid+OR+dclp_series:p.heid)&fq=(ddbdp_volume:1+OR+hgv_volume:1+OR+dclp_volume:1)&p=0&t=25

one sees 

![Bildschirmfoto 2019-05-15 um 14 23 19](https://user-images.githubusercontent.com/612992/57775321-06010d80-771d-11e9-8c17-3209626508ca.png)

and it works

**Comment by jcowey** [comment]
If you do the same in the new papyri.info
http://papyri.info/search?&COLLECTION=dclp&SERIES=p.heid&VOLUME=1
then go to the first record
http://papyri.info/dclp/59735?rows=2&start=0&fl=id,title&fq=collection:dclp&fq=(ddbdp_series:p.heid+OR+hgv_series:p.heid+OR+dclp_series:p.heid)&fq=(ddbdp_volume:1+OR+hgv_volume:1+OR+dclp_volume:1)&p=0&t=25

`Previous record Next record` does not appear.

Would you please make papyri.info work the same way as dev.papyri.info

**Comment by jcowey** [comment]
The same can be observed for ddbdp series
http://papyri.info/search?&COLLECTION=ddbdp&SERIES=p.amst&VOLUME=1
then go to the first record
http://papyri.info/ddbdp/p.amst;1;27?rows=2&start=0&fl=id,title&fq=collection:ddbdp&fq=(ddbdp_series:p.amst+OR+hgv_series:p.amst+OR+dclp_series:p.amst)&fq=(ddbdp_volume:1+OR+hgv_volume:1+OR+dclp_volume:1)&p=0&t=72

`<<Previous record Next record>>`
does not appear.

**Comment by hcayless** [comment]
@jcowey try doing a hard refresh on your browser (hold down the shift key and reload). I think this is a Javascript caching issue (it's changed, but your browser still has the old copy).

**Comment by jcowey** [comment]
Gosh if only all bugs were that easy to solve. Thank you! I am not functioning properly ;) - should have thought of that
