### ISSUE TITLE
Incomplete Search Results

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#47]
I'm getting different search results for the same search string in papyri.info and litpap.info.

Entering γραμμ ερμην in litpap.info yields 64 results

http://litpap.info/search?STRING=(%CE%B3%CF%81%CE%B1%CE%BC%CE%BC+%CE%B5%CF%81%CE%BC%CE%B7%CE%BD)&no_caps=on&no_marks=on&target=text&DATE_MODE=LOOSE&DOCS_PER_PAGE=15

whereas γραμμ AND ερμην in papyri.info yields only 50

http://www.papyri.info/search?STRING=(%CE%B3%CF%81%CE%B1%CE%BC%CE%BC)%C2%A4(AND+%CE%B5%CF%81%CE%BC%CE%B7%CE%BD)&no_caps=on&no_marks=on&target=text&DATE_MODE=LOOSE&DOCS_PER_PAGE=15

Interestingly, the papyri.info search doesn’t catch this, where ερμην is in the apparatus.

http://litpap.info/ddbdp/bgu;16;2594/?q=SUBSTRING:(%CE%B3%CF%81%CE%B1%CE%BC%CE%BC+%CE%B5%CF%81%CE%BC%CE%B7%CE%BD)&rows=3&start=2&fl=id%2Ctitle&fq=transcription_ngram_ia%3A%28%CE%B3%CF%81%CE%B1%CE%BC%CE%BC+%CE%B5%CF%81%CE%BC%CE%B7%CE%BD%29&sort=series+asc%2Cvolume+asc%2Citem+asc&p=3&t=63

**Comment by hcayless** [comment]
Think this is now fixed. Papyri.info returns 65 results (including one that litpap doesn't have).
