### ISSUE TITLE
Display in browser tabs

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#49]
I called up papyri.info and have six tabs open: papyri.info entry page, PN search page (hit the Search data button), home user_dashboard, DDB board, HGV board, DCLP board.

This is what they look like:

![Bildschirmfoto 2019-05-23 um 17 37 13](https://user-images.githubusercontent.com/612992/58266183-77763700-7d81-11e9-82e6-6aaacc805b9b.png)

Papyri.info | PN Search | DCLP | DCLP | DCLP | DCLP

We do not want DCLP appearing here. I have forgotten what it used to be when one was in the boards before DCLP was part of the system. There might be a nice argument for displaying DCLP for the DCLP board, DDB for the DDB board, HGV for the HGV board, APIS for all the APIS boards, Transl for the Translation board. 

For an editor who is working that would be very helpful.

If, however, that is more work, then please replace DCLP with Papyri.info or whatever it used to be.

**Comment by jcowey** [comment]
It would be nice, if whenever one was in DCLP 
http://papyri.info/editor/user/board_dashboard?board_id=60
http://papyri.info/browse/dclp/
http://papyri.info/authors
http://papyri.info/search?&COLLECTION=dclp&SERIES=o.theb.copt
http://papyri.info/browse/dclp/p.oxy
http://papyri.info/search?&COLLECTION=dclp&SERIES=p.oxy&VOLUME=27

Wherever "dclp" is part of the URL
and
http://papyri.info/authors

The colour in the banner is Blue instead of Red

Red = original papyri.info
Blue = literary stuff (the blue used in litpap.info)

We have already had mix ups with people adding DCLP texts to DDB records. I feel that colour might reduce these sorts of mistakes

**Comment by hcayless** [comment]
This has been fixed for a while but the ticket didn't get closed.
