### ISSUE TITLE
Inconsistency in TM search

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#51]
http://papyri.info/#
enter 8988 
leads to http://papyri.info/ddbdp/bgu;1;224dupl
So fine. For ddbdp/hgv files things work well.

Back to the same search interface http://papyri.info/#
enter 64248
I get no hit but see this
![Bildschirmfoto 2019-06-05 um 21 24 16](https://user-images.githubusercontent.com/612992/58984028-54fc0900-87d8-11e9-969a-418e3d94cf72.png)

So I decided to look for that number another way.
http://papyri.info/browse/dclp/
http://papyri.info/search?&COLLECTION=dclp&SERIES=tm
now I enter 64248 into the ID # box
![Bildschirmfoto 2019-06-05 um 21 26 35](https://user-images.githubusercontent.com/612992/58984163-a5736680-87d8-11e9-8f0f-d5e7caae21ae.png)

No hits and I see this
![Bildschirmfoto 2019-06-05 um 21 27 16](https://user-images.githubusercontent.com/612992/58984215-c0de7180-87d8-11e9-8c84-1af935b51255.png)

but I know that this TM number is in the system
http://papyri.info/dclp/64248

So searching for a TM number that is anchored in the DCLP world is not functioning as we would like it to.

**Comment by hcayless** [comment]
The TM lookup is working now, and that record is actually m.pern.s;3;10, so idno won't be the TM number. I have verified that it works for things in tm;;*
