### ISSUE TITLE
HGV series display not working as would be liked

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#52]
Browsing by HGV
http://papyri.info/browse/hgv/
then to series and volume we get the following
http://papyri.info/search?SERIES=P.Oxy.&VOLUME=83
where only those numbers which already have a relevant ddbdp file are displayed.

Here we would like to see a list of all P.Oxy. 83 numbers for which there is no text added. This is the way most people locate files in order to add the relevant Greek / Latin / Coptic text.

Would you please make it work again in that way.

**Comment by hcayless** [comment]
Not totally sure when it was fixed, but this appears to me to be working now.
