### ISSUE TITLE
DCLP Results Discrepancies

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#53]
There's a large discrepancy in the PN between the number of DCLP records appearing under Collection in litpap and those in papyri.info. The former shows 14636 ([see here](http://litpap.info/search?DATE_MODE=LOOSE&DOCS_PER_PAGE=15&COLLECTION=dclp)) and the latter 10211 ([see here](http://www.papyri.info/search?DATE_MODE=LOOSE&DOCS_PER_PAGE=15&COLLECTION=dclp))  records; you’ll notice that the first 4 hits on the litpap page are absent from the papyinfo page.  What is related, if you navigate to P.Herc. in the Series menu, you’ll find that litpap displays 232 hits ([litpap p.herc.](http://litpap.info/search?DATE_MODE=LOOSE&DOCS_PER_PAGE=15&SERIES=dclp%3Ap.herc)) whereas papyinfo shows 67 (http://www.papyri.info/search?DATE_MODE=LOOSE&DOCS_PER_PAGE=15&SERIES=dclp%3Ap.herc).  As far as I can tell, files are not actually missing from papyri.info, they’re just not appearing in the PN.

**Comment by hcayless** [comment]
Fixed
