### ISSUE TITLE
Journal and volume not displaying in Biblio

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#54]
There are several display problems in Biblio:  journal and volume no. are not being surfaced; article titles are being duplicated (one in quotation marks, the other in italics).  Here's an example

http://www.papyri.info/biblio/95357?q=keyes

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/commit/3df0bb84ebbdeff59c34fb8fd6b6993576391f38
should solve 
http://www.papyri.info/biblio/95357

**Comment by jcowey** [comment]
|[95342](https://github.com/papyri/idp.data/blob/master/Biblio/96/95342.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/268"/>`|commit|
|[95343](https://github.com/papyri/idp.data/blob/master/Biblio/96/95343.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/460"/>`|commit|
|[95345](https://github.com/papyri/idp.data/blob/master/Biblio/96/95345.xml#L17)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/1270"/>`|commit|
|[95346](https://github.com/papyri/idp.data/blob/master/Biblio/96/95346.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/1241"/>`|commit|
|[95348](https://github.com/papyri/idp.data/blob/master/Biblio/96/95348.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/182"/>`|commit|
|[95355](https://github.com/papyri/idp.data/blob/master/Biblio/96/95355.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/261"/>`|commit|
|[95356](https://github.com/papyri/idp.data/blob/master/Biblio/96/95356.xml#L19)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/113"/>`|commit|
|[95357](https://github.com/papyri/idp.data/blob/master/Biblio/96/95357.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/40"/>`|commit|
|[95358](https://github.com/papyri/idp.data/blob/master/Biblio/96/95358.xml#L15)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/268"/>`|commit|
|[95360](https://github.com/papyri/idp.data/blob/master/Biblio/96/95360.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/1342"/>`|commit|
|[95361](https://github.com/papyri/idp.data/blob/master/Biblio/96/95361.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/83"/>`|commit|
|[95372](https://github.com/papyri/idp.data/blob/master/Biblio/96/95372.xml#L15)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/95371"/>`|commit|
|[95382](https://github.com/papyri/idp.data/blob/master/Biblio/96/95382.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/184"/>`|commit|
|[95433](https://github.com/papyri/idp.data/blob/master/Biblio/96/95433.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95435](https://github.com/papyri/idp.data/blob/master/Biblio/96/95435.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95438](https://github.com/papyri/idp.data/blob/master/Biblio/96/95438.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95441](https://github.com/papyri/idp.data/blob/master/Biblio/96/95441.xml#L14)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/511"/>`|commit|
|[95442](https://github.com/papyri/idp.data/blob/master/Biblio/96/95442.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/511"/>`|commit|
|[95443](https://github.com/papyri/idp.data/blob/master/Biblio/96/95443.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95444](https://github.com/papyri/idp.data/blob/master/Biblio/96/95444.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95462](https://github.com/papyri/idp.data/blob/master/Biblio/96/95462.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/511"/>`|commit|
|[95466](https://github.com/papyri/idp.data/blob/master/Biblio/96/95466.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/40"/>`|commit|

**Comment by jcowey** [comment]
|[95342](https://github.com/papyri/idp.data/blob/master/Biblio/96/95342.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/268"/>`|commit|
|[95343](https://github.com/papyri/idp.data/blob/master/Biblio/96/95343.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/460"/>`|commit|
|[95345](https://github.com/papyri/idp.data/blob/master/Biblio/96/95345.xml#L17)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/1270"/>`|commit|
|[95346](https://github.com/papyri/idp.data/blob/master/Biblio/96/95346.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/1241"/>`|commit|
|[95348](https://github.com/papyri/idp.data/blob/master/Biblio/96/95348.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/182"/>`|commit|
|[95355](https://github.com/papyri/idp.data/blob/master/Biblio/96/95355.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/261"/>`|commit|
|[95356](https://github.com/papyri/idp.data/blob/master/Biblio/96/95356.xml#L19)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/113"/>`|commit|
|[95357](https://github.com/papyri/idp.data/blob/master/Biblio/96/95357.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/40"/>`|commit|
|[95358](https://github.com/papyri/idp.data/blob/master/Biblio/96/95358.xml#L15)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/268"/>`|commit|
|[95360](https://github.com/papyri/idp.data/blob/master/Biblio/96/95360.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/1342"/>`|commit|
|[95361](https://github.com/papyri/idp.data/blob/master/Biblio/96/95361.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/83"/>`|commit|
|[95372](https://github.com/papyri/idp.data/blob/master/Biblio/96/95372.xml#L15)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/95371"/>`|commit|
|[95382](https://github.com/papyri/idp.data/blob/master/Biblio/96/95382.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/184"/>`|commit|
|[95433](https://github.com/papyri/idp.data/blob/master/Biblio/96/95433.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95435](https://github.com/papyri/idp.data/blob/master/Biblio/96/95435.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95438](https://github.com/papyri/idp.data/blob/master/Biblio/96/95438.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95441](https://github.com/papyri/idp.data/blob/master/Biblio/96/95441.xml#L14)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/511"/>`|commit|
|[95442](https://github.com/papyri/idp.data/blob/master/Biblio/96/95442.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/511"/>`|commit|
|[95443](https://github.com/papyri/idp.data/blob/master/Biblio/96/95443.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95444](https://github.com/papyri/idp.data/blob/master/Biblio/96/95444.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/110"/>`|commit|
|[95462](https://github.com/papyri/idp.data/blob/master/Biblio/96/95462.xml#L13)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/511"/>`|commit|
|[95466](https://github.com/papyri/idp.data/blob/master/Biblio/96/95466.xml#L12)|`<ptr target="http://papyri.info/biblio/papyri.info/biblio/40"/>`|commit|

**Comment by jcowey** [comment]
All now corrected and looking good.
--
http://papyri.info/biblio/95342
http://papyri.info/biblio/95343
http://papyri.info/biblio/95345
http://papyri.info/biblio/95346
http://papyri.info/biblio/95348
http://papyri.info/biblio/95355
http://papyri.info/biblio/95356
http://papyri.info/biblio/95357
http://papyri.info/biblio/95358
http://papyri.info/biblio/95360
http://papyri.info/biblio/95361
http://papyri.info/biblio/95372
http://papyri.info/biblio/95382
http://papyri.info/biblio/95433
http://papyri.info/biblio/95435
http://papyri.info/biblio/95438
http://papyri.info/biblio/95441
http://papyri.info/biblio/95442
http://papyri.info/biblio/95443
http://papyri.info/biblio/95444
http://papyri.info/biblio/95462
http://papyri.info/biblio/95466
