### ISSUE TITLE
Frontmatter and line-by-line commentary not displaying in HTML

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#55]
The commentary subtypes "frontmatter" and "linebyline" are not displaying in the HTML. See for example
http://papyri.info/dclp/60868, where the elements given below don't appear.

<text><body><div type="commentary" subtype="frontmatter" xml:space="preserve"><p>As the editor, M. Subacus, notes, "[T]he text conforms to the vulgate tradition. Only two other papyri contain the same portion of text as this one: P.Duke inv. 970 (J. Lundon, "Homer, Iliad I 127-138 from the Duke Papyrus Collection," ZPE 141 [2002] 71-73) overlaps at lines 127-138, and P.Koln 1.21 at lines 129-146," BASP 48 (2011), 10.</p></div>

<div type="commentary" subtype="linebyline"><list><item corresp="#lb17" xml:space="preserve"><ref>16</ref><p>Scribal error: ἐς' δ for ἐς δ'</p></item></list></div>

**Comment by jcowey** [comment]
The XML for frontmatter is fine:
https://github.com/papyri/idp.data/blob/master/DCLP/61/60868.xml#L135

The XML for commentary is fine:
https://github.com/papyri/idp.data/blob/master/DCLP/61/60868.xml#L161-L168

**Comment by jcowey** [comment]
Would you please tweak the necessary transformations to make sure this is displayed in HTML

**Comment by hcayless** [comment]
This appears to have been fixed and I forgot to close it.
