### ISSUE TITLE
Search not finding a known instance

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#56]
A search for #αχρεια# yielded 7 hits.

![Bildschirmfoto 2019-06-28 um 14 54 02](https://user-images.githubusercontent.com/612992/60343620-b3ba3a00-99b4-11e9-8f90-8b04eebef816.png)

**Comment by jcowey** [comment]
Why does it not find

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.mil.congr.xviii/p.mil.congr.xviii.pg38.xml#L50

`<lb n="1"/>ἀχρεῖα </ab></div>`

**Comment by hcayless** [comment]
Fixed with d173729.
