### ISSUE TITLE
Error in search result order

### ISSUE THREAD

**Issue by hcayless** [papyri/navigator#57]
http://papyri.info/search?STRING1=cairo&target1=METADATA&no_caps1=on&no_marks1=on&COLLECTION=nyu&page=10 gives the expected order, but clicking on the first item and then "next" does not result in going to the next item in the original search result. Looks like the correct ordering isn't being applied during navigation through a search result.

**Comment by jcowey** [comment]
This mixed up order happens in both DDbDP and HGV searches:
http://papyri.info/search?&COLLECTION=ddbdp&SERIES=p.aberd
clicking on any of the hits takes you to that hit but then "Previous record" and "Next record" is random.
http://papyri.info/search?SERIES=O.Wilck.
Likewise

**Comment by hcayless** [comment]
Fixed. Closing
