### ISSUE TITLE
TM number search not working for docs with 2 HGV numbers

### ISSUE THREAD

**Issue by enury** [papyri/navigator#58]
My colleagues and I have noticed that a search for TM number
13 (http://papyri.info/ddbdp/p.adl;;G13) 
was not yielding any result:

![image](https://user-images.githubusercontent.com/8657997/65027116-0fec8480-d93a-11e9-8c84-4fe45ade52e9.png)

Once we land on this page, any TM number search will not work. We have to go back to the homepage (or any other page) to start a new TM number search.

Today we discovered that the same problem happens when searching for 
20818 and 20819 (http://papyri.info/ddbdp/p.tebt;2;340)

We suspect this might happen to documents that have two HGV numbers. It seemed to be confirmed when searching for TM 9 (http://papyri.info/ddbdp/p.adl;;G9).

**EDIT**

More TM numbers that don't come up in a search: 2339, 7411, 12786, 12787, 12788, 28932, 78586 and 78587.

**Comment by hcayless** [comment]
This is fixed, but won't be globally available until we do a full reindex, which I will do this weekend.
