### ISSUE TITLE
Aggregating APIS records with DCLP records for display in PN

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#61]
http://papyri.info/dclp/60846
aggregates DCLP metadata, Trismegistos metadata and DCLP text.

![Bildschirmfoto 2019-11-06 um 22 21 30](https://user-images.githubusercontent.com/612992/68339119-3f22a500-00e4-11ea-8907-1a41e29d73e0.png)

http://papyri.info/apis/michigan.apis.1337
belongs to the above aggregation and should be aggregated with the above.

![Bildschirmfoto 2019-11-06 um 22 21 04](https://user-images.githubusercontent.com/612992/68339144-4cd82a80-00e4-11ea-91cf-b0b907287eca.png)

When looking at the idnos in the DCLP Metadata/Text file the following are found
https://github.com/papyri/idp.data/blob/master/DCLP/61/60846.xml#L11-L16

```
            <idno type="dclp">60846</idno>
            <idno type="TM">60846</idno>
            <idno type="LDAB">1974</idno>
            <idno type="filename">60846</idno>
            <idno type="dclp-hybrid">tm;;60846</idno>
            <idno type="MP3">0693.2</idno>
```

I found the relevant section in the APIS record at
https://github.com/papyri/idp.data/blob/master/APIS/michigan/xml/michigan.apis.1337.xml#L12-L13

```
            <idno type="apisid">michigan.apis.1337</idno>
            <idno type="controlNo">(MiU)1337</idno>
```

Hoping that by adding the relevant idnos to the APIS record I would be able to have the system (through the sync process) aggregate all the files together in PN I changed the idnos in the APIS file

https://github.com/papyri/idp.data/commit/2019764ded65bdf6a4a14cb940c3e9071a76a067

The idnos are now to be found like this:

https://github.com/papyri/idp.data/blob/master/APIS/michigan/xml/michigan.apis.1337.xml#L12-L16

```
            <idno type="apisid">michigan.apis.1337</idno>
            <idno type="controlNo">(MiU)1337</idno>
            <idno type="TM">60846</idno>
            <idno type="dclp">60846</idno>
            <idno type="dclp-hybrid">tm;;60846</idno>
```

I shall now wait for the next sync. I reckon that the APIS file

http://papyri.info/apis/michigan.apis.1337

will aggregate APIS and Trismegistos

but APIS will not be aggregated alongside DCLP and Trismegistos under 

http://papyri.info/dclp/60846

If this is so, would you please tweak sync so that under
http://papyri.info/dclp/60846

DCLP metadata, Trismegistos, APIS and DCLP text are all aggregated together and thus displayed together in PN.

**Comment by jcowey** [comment]
And my analysis was indeed correct:

![Bildschirmfoto 2019-11-06 um 22 43 28](https://user-images.githubusercontent.com/612992/68340581-f91b1080-00e6-11ea-9973-091657241684.png)

http://papyri.info/apis/michigan.apis.1337
aggregates and displays together APIS and Trismegistos


http://papyri.info/dclp/60846

remains unchanged in display in PN (aggregating only DCLP metadata, Trismegistos metadata and DCLP text)

**Comment by hcayless** [comment]
This looks like a mapping problem. Look at fixing the APIS -> RDF XSLT to make sure it picks up DDb/HGV/DCLP idnos. It never had to look for them initially.

**Comment by hcayless** [comment]
Further thought: pn-indexer might require some tweaking too, as I'm not certain it will do the right thing given an APIS filename as input with a need to aggregate it with DCLP—rather than aggregate DCLP to it.

**Comment by jcowey** [comment]
http://papyri.info/dclp/65823
was finalised 2019-12-18.
with the following idnos
https://github.com/papyri/idp.data/blob/master/DCLP/66/65823.xml#L11-L16
```
            <idno type="dclp">65823</idno>
            <idno type="TM">65823</idno>
            <idno type="LDAB">7079</idno>
            <idno type="filename">65823</idno>
            <idno type="dclp-hybrid">tm;;65823</idno>
            <idno type="MP3">1596.1</idno>
```

http://papyri.info/apis/michigan.apis.3416
was finalised 2019-12-18
with the following commit
https://github.com/papyri/idp.data/commit/c3c91c50747213a71ddb12e0ac0b82b8aa0b9c60

here are the idnos:
at
https://github.com/papyri/idp.data/blob/master/APIS/michigan/xml/michigan.apis.3416.xml#L12-L16
```
            <idno type="apisid">michigan.apis.3416</idno>
            <idno type="controlNo">(MiU)3416</idno>
            <idno type="TM">65823</idno>
            <idno type="dclp">65823</idno>
            <idno type="dclp-hybrid">tm;;65823</idno>
```

It is the case that 
http://papyri.info/dclp/65823
and
http://papyri.info/apis/michigan.apis.3416

are *not* being aggregated.

I assume that something in the sync process is still not fully functional.

**Comment by hcayless** [comment]
Think this is fixed now.
