### ISSUE TITLE
texts submitted to DCLP disappear

### ISSUE THREAD

**Issue by HolgerEssler** [papyri/navigator#62]
Some texts, when submitted to the DCLP-board through the editor seem to disappear and not reach the board (also failing to be included in the News Feed).
Examples are:
TM 59474 submitted by me on 11 november 2019 (http://www.papyri.info/editor/publications/80510)
TM 67962 submitted by me on 2 december 2019  (http://www.papyri.info/editor/publications/79138)
and 653666, SoSOL 2017 512 (http://www.papyri.info/editor/publications/61442), submitted by elisabetta.alletto@gmail.com on 15 november 2019

**Comment by rla2118** [comment]
There are also files that have been successfully committed to GitHub but still do not display in DCLP.  Here's an example:

https://github.com/papyri/idp.data/tree/master/DCLP/65
shows that
https://github.com/papyri/idp.data/blob/master/DCLP/65/64427.xml
was changed.

https://github.com/papyri/idp.data/blob/master/DCLP/65/64427.xml#L108-L118
shows the text which was entered with the date stamps
https://github.com/papyri/idp.data/blob/master/DCLP/65/64427.xml#L97-L105

**Comment by rla2118** [comment]
I want to give another example, which may or may not be related to the preceding.

TM 65682 does not display at
http://papyri.info/dclp/65682

even though there is an XML file in GitHub:
https://github.com/papyri/idp.data/blob/master/DCLP/66/65682.xml

which does display in litpap.info
http://litpap.info/dclp/65682

**Comment by hcayless** [comment]
I've fixed the pages that weren't displaying. The submissions that went straight to "committed" status I'm going to assign to Ryan.

**Comment by ryanfb** [comment]
Commenting here for my own tracking purposes:

- [ ] 80510
- [ ] 79138
- [ ] 61442

**Comment by ryanfb** [comment]
Should all now be submitted. NB: 61442 went to HGV Meta board first.
