### ISSUE TITLE
Display of analpap files

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#63]
Two analpap files are not displaying properly in papyri.info

http://papyri.info/ddbdp/analpap;21_22;89
and
http://papyri.info/ddbdp/analpap;21_22;89

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV643/642461.xml#L10-L13
matches
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/analpap/analpap.21_22/analpap.21_22.89.xml#L11-L14

**Comment by jcowey** [comment]
and
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV643/642462.xml#L10-L13
matches
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV643/642462.xml#L10-L13

**Comment by jcowey** [comment]
But something still appears to be wrong and display is not working. Would you please fix this.
Strange because I waited until after the re-index you did recently before finalizing these files.

**Comment by hcayless** [comment]
Fixed.
