### ISSUE TITLE
Two finalized DCLP files do not display properly

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#64]
http://papyri.info/dclp/59956
https://github.com/papyri/idp.data/blob/master/DCLP/60/59956.xml

http://papyri.info/dclp/63954
https://github.com/papyri/idp.data/blob/master/DCLP/64/63954.xml

Both of these files (59956 and 63954) display as follows:

![Bildschirmfoto 2020-01-16 um 16 49 07](https://user-images.githubusercontent.com/612992/72539854-443c6700-3880-11ea-8e4f-7d78c22128a3.png)

and

![Bildschirmfoto 2020-01-16 um 16 49 32](https://user-images.githubusercontent.com/612992/72539873-4b637500-3880-11ea-885b-90adfa81ad3e.png)

although it seems to me that the xml files are OK

**Comment by jcowey** [comment]
59956 is 557 code lines long. That is a long file.
63954 is 168 code lines long. 

Have tested both in oXygen. They validate.

**Comment by jcowey** [comment]
If you can make them display in DCLP easily please do so. They are part of a project that is planning to demonstrate next week and it would be nice if they were visible.

**Comment by jcowey** [comment]
63954 was called up through Advanced create using the PN ID function. Changes were made, resubmitted and is now visible:

http://papyri.info/dclp/63954

Same done for 59956. Unfortunately it is still NOT showing up properly.
http://papyri.info/dclp/59956
https://github.com/papyri/idp.data/blob/master/DCLP/60/59956.xml

**Comment by hcayless** [comment]
I've fixed the bug that was being triggered. Both have issues in the bibliography. 59956 has two principal editions, and 63954 has none. The latter also has a subtype "palaeo", which the XSLT isn't sure what to do with.
