### ISSUE TITLE
Text supplied from parallel not found in search

### ISSUE THREAD

**Issue by HolgerEssler** [papyri/navigator#67]
BKT X 1 (http://papyri.info/dclp/175242) is a Homer papyrus almost entirely supplemented from the medieval tradition. The encoding (rightly I would say) uses the supplied-element with the attributes reason="lost" and evidence="parallel". However, none of the supplied words will be found in a text search (I tried προσαμύνομεν in line 1, λωβήσαιο in line 5). On the contrary, in other examples without the attribute evidence="parallel" the supplied text is found in a search. Thus I suppose this to be a bug depending on the attribute evidence="parallel" .
On a separate page is the question, whether or not this kind of supplements should be tagged throughout with evidence="parallel" (I am inclined to "yes"). BKT X 2 (http://papyri.info/dclp/154389) for instance is not, although the amount of text preserved in each line is not much higher.

**Comment by hcayless** [comment]
This is indeed a bug. Turns out it's a sloppy bit of regex matching in the EpiDoc stylesheets, but there are adjustments to be made in the PN Stylesheets as well, which should fix it.

**Comment by hcayless** [comment]
Works now. Closing
