### ISSUE TITLE
Provide new URLs for link to source for HGV

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#7]
When the Navigator displays the aggregated Metadata and Text files, there is a link to the source of the Metadata (i.e. Link back to HGV). E.g. go to 
http://papyri.info/ddbdp/bgu;6;1215
one sees
BGU 6 1215 [source] [xml] 
when one clicks [source] it goes to
http://aquila.papy.uni-heidelberg.de/Hauptregister/FMPro?-db=hauptregister_&TM_Nr.=7306&-format=DTableVw.htm&-lay=Liste&-find
where TM_Nr.=7306, was how this was built
It should now go to 
http://aquila.zaw.uni-heidelberg.de/hgv/7306
This is built analogously to when on clicks on [xml]
http://papyri.info/hgv/7306/source

**Comment by jcowey** [comment]
I introduce this analogy because when the „HGV“ number is not simply a digit e.g.
http://papyri.info/ddbdp/p.adl;;G3
where one sees
P.Adler 3 Kol. I - III 4 [source] [xml] 
And
P.Adler 3 Kol. III 5 - 11 [source] [xml] 
then it is the „HGV“ number which is important to extract, so
for
P.Adler 3 Kol. I - III 4 [source] [xml] 
http://papyri.info/hgv/2a/source
→ 
http://aquila.zaw.uni-heidelberg.de/hgv/2a

and
P.Adler 3 Kol. III 5 - 11 [source] [xml] 
http://papyri.info/hgv/2b/source
→
http://aquila.zaw.uni-heidelberg.de/hgv/2b

**Comment by hcayless** [comment]
Changed link. Will require a rebuild of the site pages to appear online.

**Comment by jcowey** [comment]
May I please ask you to do a rebuild of the site pages, so that the link appears online. Just in the last few days I have had people ask me why the links do not work any more.

**Comment by jcowey** [comment]
no fixed
