### ISSUE TITLE
Non displaying files

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#73]
In the case of three "new" series:
http://papyri.info/browse/ddbdp/chiron
http://papyri.info/search?&COLLECTION=ddbdp&SERIES=p.bastianini
http://papyri.info/search?&COLLECTION=ddbdp&SERIES=p.nekr
when the reindex of two weeks ago was done then the existing files were matched up by mapping and sync and display nicely:
http://papyri.info/ddbdp/p.nekr;;2
http://papyri.info/ddbdp/p.bastianini;;25
http://papyri.info/ddbdp/p.bastianini;;11
http://papyri.info/ddbdp/chiron;44;325
http://papyri.info/ddbdp/chiron;49;275_3
http://papyri.info/ddbdp/chiron;49;286_5
But when I started adding more to these series, they no longer display properly:
http://papyri.info/ddbdp/p.nekr;;3
http://papyri.info/ddbdp/p.bastianini;;14
http://papyri.info/ddbdp/chiron;49;274_2
http://papyri.info/ddbdp/chiron;49;273_1

The relevant idnos are all correct.

Would you please try to sort this as I have 10 new bastianini files I would like to commit and 7 new chiron;49 files as well as several p.nekr. files which are coming in from the editor.

**Comment by jcowey** [comment]
Noticed that you made a merge yesterday:
https://github.com/papyri/navigator/commit/47dfac8bf98b26d523ecc5b90495345e4cc9b33e

Does that in any way affect how sync will now work? Might it improve the problems outlined above?

**Comment by hcayless** [comment]
Ran the reindex and those pages are now displaying.
