### ISSUE TITLE
Display Problem, bgu;16;2629

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#8]
@ http://papyri.info/ddbdp/bgu;16;2629 
In line 16 of this text, there is the word ε̣ἶ̣ναι. It appears correctly in the git file:
`<unclear>εἶ</unclear>ναι`
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/bgu/bgu.16/bgu.16.2629.xml#L106
but the HTML display leaves out the soft breathing mark, ε̣ῖ̣ναι(*).

ματέως ἄγνοι̣α̣ν̣ ε̣ῖ̣ναι(*), τὸ πρότερον φάσκων μη-

**Comment by jcowey** [comment]
Appears to work now!!
