### ISSUE TITLE
Tweak search to accommodate <space extent="unknown" unit="character"/>

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#83]
A search for #Ηρακλουσ#
http://papyri.info/search?STRING1=%23%CE%97%CF%81%CE%B1%CE%BA%CE%BB%CE%BF%CF%85%CF%83%23&target1=TEXT&no_caps1=on&no_marks1=on&page=1
does not include a hit for sb.26.16378
in lines 14-15 of that text the search term is broken across lines and a vacat was encoded between the second and third syllable
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/sb/sb.26/sb.26.16378.xml#L67-L68:

```
<lb n="14"/><num value="6">ϛ</num> <expan><unclear>ἡ</unclear><ex>μέρας</ex></expan> Ἡρακ
<lb n="15" break="no"/><space extent="unknown" unit="character"/>λοῦς.
```

It would be great, if search could be tweaked so that `<space extent="unknown" unit="character"/>` when preceded by letters and followed by letters (with no white space on either side of the tag) does not prevent the return of the letters searched for. I am assuming that my analysis is correct. Perhaps there is some other reason for this case (concatenation of `<lb n="15" break="no"/><space extent="unknown" unit="character"/>`)

**Comment by jcowey** [comment]
Just noticed that this is related to #92

**Comment by hcayless** [comment]
Verified that this is fixed
