### ISSUE TITLE
Volumes not visible thru DDbDP / HGV browse

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#87]
There is a recurring problem with some series / volumes which do not appear when a user navigates the browser via 
http://papyri.info/browse/ddbdp/
and / or
http://papyri.info/browse/hgv/

At present this affects p.berl.cohen / P.Berl. Cohen. (as reported to me by mail, today 23 October 2020 by Jean-Luc Fournet)
http://papyri.info/search?&COLLECTION=ddbdp&SERIES=p.berl.cohen
returns nothing
![Bildschirmfoto 2020-10-23 um 15 03 17](https://user-images.githubusercontent.com/612992/97006955-ec363d80-1540-11eb-9555-13319385a22a.png)

http://papyri.info/search?SERIES=P.Berl._Cohen
returns one hit
![Bildschirmfoto 2020-10-23 um 15 03 50](https://user-images.githubusercontent.com/612992/97007006-04a65800-1541-11eb-9a98-951775568348.png)

There are 20 files in github for p.berl.cohen all of which ought to appear in the above browse searches.
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.berl.cohen

**Comment by jcowey** [comment]
On 1 September
Nina Sietis reported the following:
"I was trying to use the DDbDP and I have some problems with P.Prag.: when you click on P.Prag. and then on P.Prag. 3 no result is displayed, whilst only one result is shown if you click on P.Prag. 1. I am sure that a couple of months ago everything worked properly and if you go to a specific papyrus on papyri.info <http://papyri.info/> through the link on TM everything seems ok. As far as I can check, the problem does not seem to affect other collections."

I asked her to report this to Hugh, which as far as I remember she did. Hugh was able to fix that specific problem.

**Comment by jcowey** [comment]
On 14 September
Anna Monte reported a similar observation: 

today I observed a curious phenomenon in papyri.info. If I search for P.Wash.Univ. in the DDBDP I don't find it, but if I search it on TM I find a link to the DDBDP which works

Again as far as I remember she contacted Hugh and he was able to fix the problem for P.Wash.Univ.

**Comment by hcayless** [comment]
I think these are fixed. There were some issues with the indexing process generating malformed Solr documents, which I think crept in with the DCLP XSLT merge. There may be some further cleanup to do there, but I think I've fixed the problems.
