### ISSUE TITLE
Serious search problems

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#88]
Today, 23 October 2020, I received a mail from Jean Luc Fournet, in which he asked me for help with two problems. First problem was not finding lists of files in specific volumes when browsing papyri.info using
http://papyri.info/browse/ddbdp/
and
http://papyri.info/browse/hgv/

I created an issue for that at #87

**Comment by jcowey** [comment]
The other problem Jean Luc Fournet surfaced is  a very serious problem because when a user searches, she or he expects to be given a trustworthy series of "hits". There is evidence at present that this is *not* happening.

"Papyri.info: par exemple, http://papyri.info/ddbdp/p.berl.cohen;;1 . Si l'on fait une recherche lexicale dans papyri.info > Data (par ex. "Παπαιτος αμασιοσ"), le P.Berl.Cohen 1 ne sort pas alors qu'il contient cette séquence."

in
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.berl.cohen/p.berl.cohen.1.xml#L58
```
<lb n="4"/><gap reason="lost" quantity="2" unit="character"/>μ<gap reason="lost" quantity="3" unit="character" precision="low"/><gap reason="illegible" quantity="1" unit="character"/>ς <expan>Παπάϊτο<ex>ς</ex></expan> <expan>Ἀ<unclear>μάσ</unclear>ι<ex>ος</ex></expan> <expan>συντ<ex>άξιμον</ex></expan> <expan><unclear>κ</unclear><supplied reason="lost">ώμ<ex>ης</ex></supplied></expan>
```

specifically
```
<expan>Παπάϊτο<ex>ς</ex></expan> <expan>Ἀ<unclear>μάσ</unclear>ι<ex>ος</ex></expan>
```

**Comment by jcowey** [comment]
I can add another example:
A search for ρτιτιο

http://papyri.info/search?STRING=(%CF%81%CF%84%CE%B9%CF%84%CE%B9%CE%BF)&no_caps=on&no_marks=on&target=text&DATE_MODE=LOOSE&DOCS_PER_PAGE=15

returns one hit:
which refers to
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.bon/p.bon.11.xml#L117
```
<lb n="3"/><gap reason="lost" extent="unknown" unit="character"/> Πόρτιτιος Παώπ<supplied reason="lost">ιος
```

But does not return 
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.bingen/p.bingen.27.xml#L120
which is in fact a reprint of the same text!! (that the P.Bon. 11 version ought to have been deleted is another matter)
```
<lb n="23"/><supplied reason="lost">τοῦ</supplied> Πόρτιτος, Παῶτ<supplied reason="lost">ος 
```

**Comment by ryanfb** [comment]
After a fair amount of searching, I can't find any text term that turns up `p.berl.cohen.1.xml`. So it seems like for that issue there's probably just an indexing error with this text.

For the second issue, I think the problem is more that the data itself needs a reprint-in/reprint-from relationship added to it, than it is a search problem. `p.bingen.27.xml` doesn't contain "ρτιτιο" (note the second iota). If you instead search for Πόρτιτος or ρτιτος, it's included in the current results: http://papyri.info/search?STRING=(%CE%A0%CF%8C%CF%81%CF%84%CE%B9%CF%84%CE%BF%CF%82)&no_caps=on&no_marks=on&target=text&DATE_MODE=LOOSE&DOCS_PER_PAGE=15

**Comment by jcowey** [comment]
Thanks for the feedback @ryanfb. Had not thought of the implications of the reprint-in/reprint-from relationship. Thanks.

**Comment by hcayless** [comment]
So I think what's going on here is an (understandable) confusion over how the search works:
```
Παπαιτος αμασιοσ
```
will not get you a result, but
```
"Παπαιτος αμασιοσ"
```
or
```
Παπαιτος# #αμασιοσ
```
or
```
Παπαιτος AND αμασιοσ
```
will. I'm certain this was compounded by the indexing problem referenced in #87.
