### ISSUE TITLE
Set link back to relevant APD page

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#9]
Building blocks are  
http://www.apd.gwi.uni-muenchen.de:8080/apd/show2.jsp?papname=  
Followed by the content of the idno type=”APD” tag
<idno type=”APD”>Grohmann_Apercu_p_41</idno>
e.g.
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/sb/sb.6/sb.6.9576.xml#L19

would give a link to:  
http://www.apd.gwi.uni-muenchen.de:8080/apd/show2.jsp?papname=Grohmann_Apercu_p_41

To be surfaced under “related sources” like GLRT
E.g.
http://papyri.info/ddbdp/bgu;1;39

**Comment by hcayless** [comment]
It's surfaced in the header instead, but I did this ages ago and forgot to close the issue.
