### ISSUE TITLE
vac. distorting search results, e.g. BASP 49 111

### ISSUE THREAD

**Issue by rla2118** [papyri/navigator#92]
If I search for the Greek word αιγιαλοφυλακι, I do not find the instance of it in https://papyri.info/ddbdp/basp;49;111 (line 3-4) where it is interrupted by vac.? 
αἰγιαλοφύ- 
vac. ? λακι. 

It would be preferable if the search engine ignored the vac. in these cases.

**Comment by jcowey** [comment]
Here is the XML:
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/basp/basp.49/basp.49.111.xml#L51-L52
```
                                                            αἰγιαλοφύ
<lb n="4" break="no"/><space extent="unknown" unit="character"/> λακι

```

**Comment by jcowey** [comment]
If I search for `αιγιαλοφυλακι` then one of the hits is p.mich 11 617
![Bildschirmfoto 2021-02-05 um 16 14 52](https://user-images.githubusercontent.com/612992/107051924-5495eb80-67cd-11eb-8936-9ae55acbb72f.png)

At lin10-11 the XML is like this
```
                     αἰγιαλοφύλα
    <lb n="11" break="no"/>κι
```

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.mich/p.mich.11/p.mich.11.617.xml

That suggests to me that the problem with the one above is the juxtaposition of `<lb n="\d+" break="no"/><space extent="unknown" unit="character"/>`, which needs to be treated in such a way that `αιγιαλοφυλακι`  can be found in
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/basp/basp.49/basp.49.111.xml#L51-L52

**Comment by hcayless** [comment]
I should stress that I have no memory of this, but I'm assuming that we decided at some point to preserve vacats so they could be searched for. This is obviously a difficulty if a vacat occurs in the middle of a word, as here. I can certainly remove the vacat if it occurs next to a non-word-breaking line break. I could also just dispense with them entirely...

**Comment by jcowey** [comment]
Just noticed now that this is related to #83

**Comment by hcayless** [comment]
Verified that this is fixed
