### ISSUE TITLE
Disentangle  P.Lond. 7 1938 and P.Mich. 1 10

### ISSUE THREAD

**Issue by ryanfb** [papyri/navigator#96]
http://papyri.info/hgv/2382, currently:

> p.lond.7.1938 = HGV P.Mich. 1 10 = P.Lond. 7 1938 = Trismegistos 1916 = Trismegistos 2382 = oxford-ipap.apis.535 = michigan.apis.1813 = michigan.apis.1838 = p.mich.1.11 

Seems like they've been erroneously entangled (I could be wrong about this), though I don't see where in the XML files the identifiers have gotten crossed.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.lond/p.lond.7/p.lond.7.1938.xml#L50
`<ref n="p.mich;1;11" type="reprint-from">PMich1,11</ref>`

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.mich/p.mich.1/p.mich.1.10.xml#L48
`<ref n="p.cair.zen;1;59052" type="reprint-from">PCairZen1,59052</ref>`

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.mich/p.mich.1/p.mich.1.11.xml#L47-L48
`<ref n="p.cair.zen;1;59052" type="reprint-from">PCairZen1,59052</ref>`
`<ref n="p.lond;7;1938" type="reprint-in">PLond 7,1938</ref>`

This is what is wrong in `p.mich.1.11.xml#L47`
`<ref n="p.cair.zen;1;59052" type="reprint-from">PCairZen1,59052</ref>`

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/commit/23d746fd357fdd59dfda400f01213e060dcfa6e5

should do the trick on new reindex

**Comment by ryanfb** [comment]
Fixed after reindex.
